### ISSUE TITLE
Failing to detect mod dependancy

### ISSUE THREAD

**Issue by Morpheus1101** [shadowfacts/InductionCharger#6]
This mod depends on tesla, but it is part of the mods i have in my pack which isnt being detected. fml-client-latest log @ http://pastebin.com/T39LvNjh

**Comment by brisingraerowing** [comment]
I might know what's wrong. Tesla's Mod ID is 'tesla' (all lowercase) while you have 'Tesla' (with an initial capital letter). I think Forge uses case-sensitive comparisons for Mod IDs, so this would fail.

I'll try to change it to lowercase and see if it works.

EDIT: The change fixed it, although this issue was brought about by Tesla itself by changing the Mod ID to be all lowercase.

**Comment by Morpheus1101** [comment]
Yeah i spoke to dark and he had changed his mod ID to lower case as this will be a thing as of 1.11 but not currently enforced lol

**Comment by shadowfacts** [comment]
54ff5b4af09041a5fa3eb5338b975389ff9fb3b3

Fixed in [1.1.2](https://github.com/shadowfacts/InductionCharger/releases/tag/1.10.2-1.1.2), currently pending approval on CurseForge.
